// Generates the typed API of music-assistant-client from Music Assistant's own docs:
//   api-docs/openapi-<version>.json   → src/generated/models.ts   (all data models)
//   api-docs/commands-<version>.json  → src/generated/commands.ts (args + result per command)
// Fetch new docs from a server (/api-docs/openapi.json, /api-docs/commands.json, /info) into
// api-docs/, then run:
//   npm run gen:api [-- version]     (default: the newest version in api-docs)
import fs from "node:fs";
import path from "node:path";
import { toTs } from "./type-notation.mjs";

const DOCS = "api-docs";
const OUT = "src/generated";

const version = process.argv[2] ?? newestVersion();
const openapi = readJson(`openapi-${version}.json`);
const commands = readJson(`commands-${version}.json`);
const info = fs.existsSync(path.join(DOCS, `info-${version}.json`)) ? readJson(`info-${version}.json`) : {};
const schemas = openapi.components.schemas;
const header = (what) =>
    `// Generated by tools/generate.mjs from Music Assistant ${version}${info.schema_version ? ` (schema ${info.schema_version})` : ""} — ${what}.\n// Do not edit by hand: regenerate instead.\n`;

// Schemas that are placeholders in the server's docs, mapped to what they mean on the wire
const SPECIAL = { object: "Record<string, unknown>", Any: "unknown", AsyncGenerator: "unknown[]" };

// ---- models ------------------------------------------------------------------------------------

function refName(ref) {
    return ref.split("/").pop();
}

function modelRef(name, prefix = "") {
    return SPECIAL[name] ?? `${prefix}${name}`;
}

function schemaType(s, prefix = "") {
    if (!s) return "unknown";
    let t;
    if (s.$ref) t = modelRef(refName(s.$ref), prefix);
    else if (s.oneOf || s.anyOf) t = [...new Set((s.oneOf ?? s.anyOf).map((x) => schemaType(x, prefix)))].join(" | ");
    else if (s.enum) t = s.enum.map((v) => JSON.stringify(v)).join(" | ");
    else if (s.type === "array") t = arrayOf(schemaType(s.items, prefix));
    else if (s.type === "object" || s.properties || s.additionalProperties) {
        const props = s.properties && Object.keys(s.properties).length ? inlineObject(s, prefix) : undefined;
        const rest = s.additionalProperties ? `Record<string, ${s.additionalProperties === true ? "unknown" : schemaType(s.additionalProperties, prefix)}>` : undefined;
        t = [props, rest].filter(Boolean).join(" & ") || "Record<string, unknown>";
    } else if (s.type === "integer" || s.type === "number") t = "number";
    else if (s.type === "string" || s.type === "boolean") t = s.type;
    else t = "unknown";
    return s.nullable && t !== "unknown" ? `${t} | null` : t;
}

function inlineObject(s, prefix) {
    const req = new Set(s.required ?? []);
    return `{ ${Object.entries(s.properties)
        .map(([k, v]) => `${key(k)}${req.has(k) ? "" : "?"}: ${schemaType(v, prefix)}`)
        .join("; ")} }`;
}

function arrayOf(t) {
    return /[|&]/.test(t) && !t.startsWith("{") ? `(${t})[]` : `${t}[]`;
}

function key(k) {
    return /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
}

function doc(text, indent = "") {
    if (!text) return "";
    const lines = String(text).replaceAll("*/", "*\\/").trim().split(/\r?\n/);
    return lines.length === 1 ? `${indent}/** ${lines[0]} */\n` : `${indent}/**\n${lines.map((l) => `${indent} * ${l}`.trimEnd()).join("\n")}\n${indent} */\n`;
}

function modelDecl(name, s) {
    const description = s.description?.startsWith("Enum: ") ? "" : s.description;
    if (s.type === "object" && s.properties && Object.keys(s.properties).length) {
        const req = new Set(s.required ?? []);
        const body = Object.entries(s.properties)
            .map(([k, v]) => `${doc(v.description, "    ")}    ${key(k)}${req.has(k) ? "" : "?"}: ${schemaType(v)};`)
            .join("\n");
        return `${doc(description)}export interface ${name} {\n${body}\n}\n`;
    }
    return `${doc(description)}export type ${name} = ${schemaType(s)};\n`;
}

const models = Object.entries(schemas)
    .filter(([name]) => !(name in SPECIAL))
    .map(([name, s]) => modelDecl(name, s))
    .join("\n");

// ---- commands ----------------------------------------------------------------------------------

const resolve = (name) => (name in schemas ? modelRef(name, "M.") : undefined);

const commandEntries = commands
    .slice()
    .sort((a, b) => a.command.localeCompare(b.command))
    .map((c) => {
        // Python **kwargs shows up as a required "kwargs" parameter: it really means "any extra arguments"
        const params = c.parameters.filter((p) => p.name !== "kwargs");
        const lines = params.map((p) => `${doc(p.description, "            ")}            ${key(p.name)}${p.required ? "" : "?"}: ${toTs(p.type, resolve)};`);
        if (params.length < c.parameters.length) lines.push("            /** Further filters the server passes on (Python **kwargs). */\n            [key: string]: unknown;");
        const args = lines.join("\n");
        const result = toTs(c.return_type, resolve);
        const notes = [c.summary, c.description && c.description !== c.summary ? `\n${c.description}` : "", c.required_scope ? `\n@scope ${c.required_scope}` : ""].join("");
        return `${doc(notes, "    ")}    ${JSON.stringify(c.command)}: {\n        args: {${args ? `\n${args}\n        ` : ""}};\n        result: ${result};\n    };`;
    })
    .join("\n");

const commandsTs = `${header("all API commands")}import type * as M from "./models.js";

/** Server version and schema these types were generated from. */
export const MA_API_VERSION = { server: ${JSON.stringify(version)}, schema: ${info.schema_version ?? "undefined"} } as const;

/** Every command of the Music Assistant API with its arguments and result. */
export interface MaCommands {
${commandEntries}
}

export type MaCommandName = keyof MaCommands;
export type MaCommandArgs<C extends MaCommandName> = MaCommands[C]["args"];
export type MaCommandResult<C extends MaCommandName> = MaCommands[C]["result"];
`;

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, "models.ts"), `${header("all data models")}\n${models}`);
fs.writeFileSync(path.join(OUT, "commands.ts"), commandsTs);
console.log(`generated ${Object.keys(schemas).length} models and ${commands.length} commands from Music Assistant ${version} → ${OUT}/`);

function readJson(file) {
    return JSON.parse(fs.readFileSync(path.join(DOCS, file), "utf8"));
}

function newestVersion() {
    const versions = fs
        .readdirSync(DOCS)
        .map((f) => /^commands-(.+)\.json$/.exec(f)?.[1])
        .filter(Boolean);
    return versions.sort((a, b) => a.localeCompare(b, undefined, { numeric: true })).at(-1);
}
